module.exports = Object.freeze({
  SUBMIT_CONF_APP_REQUEST: 'SUBMIT_CONF_APP_REQUEST',
  SUBMIT_CONF_APP_SUCCESS: 'SUBMIT_CONF_APP_SUCCESS',
  SUBMIT_CONF_APP_FAILURE: 'SUBMIT_CONF_APP_FAILURE',
  RESET_ALERT: 'RESET_ALERT',
  RETRIEVE_CONF_APP_REQUEST: 'RETRIEVE_CONF_APP_REQUEST',
  RETRIEVE_CONF_APP_SUCCESS: 'RETRIEVE_CONF_APP_SUCCESS',
  RETRIEVE_CONF_APP_FAILURE: 'RETRIEVE_CONF_APP_FAILURE'
})
